version: '3.7'

services:
  passwordvalidation_api:
    image: hseeberger/scala-sbt:11.0.7_1.3.10_2.13.2
    container_name: passwordvalidation_api
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ivy:/root/.ivy2
      - type: bind
        source: .
        target: /app
    command: /bin/bash -c 'sbt run'
    ports:
      - "9001:9000"
    tty: true

volumes:
  ivy: