version: '3.7'

services:
  passwordvalidation:
    image: hseeberger/scala-sbt:11.0.6_1.3.10_2.11.12
    container_name: passwordvalidation-api
    restart: unless-stopped
    volumes:
      - ivy:/root/.ivy2
      - type: bind
        source: .
        target: /app
    command: /bin/bash -c 'cd /app && sbt run'
    ports:
      - "9001:9000"
    tty: true

volumes:
  ivy: